//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string TajNumber { get; set; }
        public string Complaint { get; set; }

        public override bool Equals(object obj)
        {
            var currentPatient = obj as patient;
            return currentPatient != null &&
                   FirstName == currentPatient.FirstName &&
                   LastName == currentPatient.LastName &&
                   Address == currentPatient.Address &&
                   TajNumber == currentPatient.TajNumber &&
                   Complaint == currentPatient.Complaint;
        }
    }
}
